// Generated by CoffeeScript 1.6.2
(function() {
  var __slice = [].slice;

  (function($, window) {
    var chardinJs;

    chardinStepsJs = (function() {
      function chardinJs(el) {
        var _this = this;

        this.$el = $(el);
		
        $(window).resize(function() {
          return _this.refresh();
        });
      }
	  
  	  chardinJs.prototype._steps = function() {
    		var steps = this.$el.find('.step').get().sort(function(a, b) {
      	  return $(a).data("order") - $(b).data("order");
      	});
        
        var stepList = null;
        var curStep = null;
        
        function makeStep(data, prev) {
          return {
            prev: prev, 
            next: null, 
            data: data,
            activate: function() {
              this.data.attr("data-intro", this.data.data("step"));
            },
            deactivate: function() {
              this.data.removeAttr("data-intro");
            }
          };
        }
      
        $.each(steps, function(index, step) {
          var data = $(step);
          if(!stepList) {
            stepList = makeStep(data, null);
            curStep = stepList;
          } else {
            curStep.next = makeStep(data, curStep);
            curStep = curStep.next;
          }
        });
        
        return stepList;
  	  };
      
      chardinJs.prototype.reset = function() {
        this.steps = this._steps();
        this.curStep = this.steps;
        var step = this.steps;
        while(step) {
          step.deactivate();
          step = step.next;
        }
        return this;
      };
	  
  	  chardinJs.prototype._remove_layers = function() {
  	    var $container = this.$el;
        $container.find('.chardinjs-helper-layer').remove();
        $container.find('.chardinjs-show-element').removeClass('chardinjs-show-element');
        $container.find('.chardinjs-relative-position').removeClass('chardinjs-relative-position');
  	  };
	  
  	  chardinJs.prototype._cur_step_elements = function() {
	  	  return this.$el.find('*[data-intro]:visible');
  	  };

      chardinJs.prototype.start = function() {
        var el, _i, _len, _ref;

        if (this._overlay_visible()) {
          return false;
        }
        
        this.reload();
        this.$el.trigger('chardinStepsJs:start');
        return this;
      };
  
      chardinJs.prototype.reload = function() {
        var el, _i, _len, _ref;
        
        var already_had_overlay = this._overlay_visible();
	
        if(!this.steps || !this.curStep || (this.options.reset_on_resume && !already_had_overlay)) {
  		    this.reset();
        }
        this.curStep.activate();
        
        this._remove_layers();
        this._add_overlay_layer();

        _ref = this._cur_step_elements();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          el = _ref[_i];
          this._show_element(el);
        }
        return this;
      };
      
      chardinJs.prototype._change_step = function(direction, on_done) {
        if(this.curStep) {
          this.curStep.deactivate();
          this.curStep = this.curStep[direction];
          if(this.curStep) {
            this.curStep.activate();
            this.reload();
          } else if(on_done) {
            on_done.call(this);
          }
        }
        return this;
      };
	  
  	  chardinJs.prototype.next = function() {
        return this._change_step('next', function() {
          this.stop();
        });
  	  };
      
  	  chardinJs.prototype.prev = function() {
        return this._change_step('prev', function() {
          this.curStep = this.steps;
        });
  	  };
      
      chardinJs.prototype.goto = function(i) {
        this.reset();
        while(this.curStep && this.curStep.data.data("order") != i) {
          this.curStep = this.curStep.next;
        }
        return this.reload(); //don't worry: this knows how to handle a null curStep
      };

      chardinJs.prototype.toggle = function() {
        if (!this._overlay_visible()) {
          return this.start();
        } else {
          return this.stop();
        }
        return this;
      };

      chardinJs.prototype.refresh = function() {
        var el, _i, _len, _ref, _results;

        if (this._overlay_visible()) {
          _ref = this._cur_step_elements;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            el = _ref[_i];
            _results.push(this._position_helper_layer(el));
          }
          return _results;
        } else {
          return this;
        }
      };

      chardinJs.prototype.stop = function() {
        this.$el.find(".chardinjs-overlay").fadeOut(function() {
          return $(this).remove();
        });
        this._remove_layers();
        if (window.removeEventListener) {
          window.removeEventListener("keydown", this._onKeyDown, true);
        } else {
          if (document.detachEvent) {
            document.detachEvent("onkeydown", this._onKeyDown);
          }
        }
        this.$el.trigger('chardinStepsJs:stop');
        return this;
      };
      
      chardinJs.prototype._stop_requested = function() {
        if(this.options.click_to_dismiss) {
          this.stop();
        }
      };

      chardinJs.prototype._overlay_visible = function() {
        return this.$el.find('.chardinjs-overlay').length !== 0;
      };

      chardinJs.prototype._add_overlay_layer = function() {
        var element_position, overlay_layer, styleText,
          _this = this;

        if (this._overlay_visible()) {
          return false;
        }
        overlay_layer = document.createElement("div");
        styleText = "";
        overlay_layer.className = "chardinjs-overlay";
        if (this.$el.prop('tagName') === "BODY") {
          styleText += "top: 0;bottom: 0; left: 0;right: 0;position: fixed;";
          overlay_layer.setAttribute("style", styleText);
        } else {
          element_position = this._get_offset(this.$el.get()[0]);
          if (element_position) {
            styleText += "width: " + element_position.width + "px; height:" + element_position.height + "px; top:" + element_position.top + "px;left: " + element_position.left + "px;";
            overlay_layer.setAttribute("style", styleText);
          }
        }
        this.$el.get()[0].appendChild(overlay_layer);
        overlay_layer.onclick = function() {
          return _this._stop_requested();
        };
        return setTimeout(function() {
          styleText += "opacity: .8;opacity: .8;-ms-filter: 'progid:DXImageTransform.Microsoft.Alpha(Opacity=80)';filter: alpha(opacity=80);";
          return overlay_layer.setAttribute("style", styleText);
        }, 10);
      };

      chardinJs.prototype._get_position = function(element) {
        return element.getAttribute('data-position') || 'bottom';
      };

      chardinJs.prototype._place_tooltip = function(element) {
        var my_height, my_width, target_element_position, target_height, target_width, tooltip_layer, tooltip_layer_position;

        tooltip_layer = $(element).data('tooltip_layer');
        tooltip_layer_position = this._get_offset(tooltip_layer);
        tooltip_layer.style.top = null;
        tooltip_layer.style.right = null;
        tooltip_layer.style.bottom = null;
        tooltip_layer.style.left = null;
        switch (this._get_position(element)) {
          case "top":
          case "bottom":
            target_element_position = this._get_offset(element);
            target_width = target_element_position.width;
            my_width = $(tooltip_layer).width();
            tooltip_layer.style.left = "" + ((target_width / 2) - (tooltip_layer_position.width / 2)) + "px";
            break;
          case "left":
          case "right":
            target_element_position = this._get_offset(element);
            target_height = target_element_position.height;
            my_height = $(tooltip_layer).height();
            tooltip_layer.style.top = "" + ((target_height / 2) - (tooltip_layer_position.height / 2)) + "px";
        }
        switch (this._get_position(element)) {
          case "left":
            return tooltip_layer.style.left = "-" + (tooltip_layer_position.width - 34) + "px";
          case "right":
            return tooltip_layer.style.right = "-" + (tooltip_layer_position.width - 34) + "px";
          case "bottom":
            return tooltip_layer.style.bottom = "-" + tooltip_layer_position.height + "px";
          case "top":
            return tooltip_layer.style.top = "-" + tooltip_layer_position.height + "px";
        }
      };

      chardinJs.prototype._position_helper_layer = function(element) {
        var element_position, helper_layer;

        helper_layer = $(element).data('helper_layer');
        element_position = this._get_offset(element);
        return helper_layer.setAttribute("style", "width: " + element_position.width + "px; height:" + element_position.height + "px; top:" + element_position.top + "px; left: " + element_position.left + "px;");
      };

      chardinJs.prototype._show_element = function(element) {
        var current_element_position, element_position, helper_layer, tooltip_layer;

        element_position = this._get_offset(element);
        helper_layer = document.createElement("div");
        tooltip_layer = document.createElement("div");
        $(element).data('helper_layer', helper_layer).data('tooltip_layer', tooltip_layer);
        if (element.id) {
          helper_layer.setAttribute("data-id", element.id);
        }
        helper_layer.className = "chardinjs-helper-layer chardinjs-" + (this._get_position(element));
        this._position_helper_layer(element);
        this.$el.get()[0].appendChild(helper_layer);
        tooltip_layer.className = "chardinjs-tooltip chardinjs-" + (this._get_position(element));
        tooltip_layer.innerHTML = "<div class='chardinjs-tooltiptext'>" + (element.getAttribute('data-intro')) + "</div>";
        helper_layer.appendChild(tooltip_layer);
        this._place_tooltip(element);
        element.className += " chardinjs-show-element";
        current_element_position = "";
        if (element.currentStyle) {
          current_element_position = element.currentStyle["position"];
        } else {
          if (document.defaultView && document.defaultView.getComputedStyle) {
            current_element_position = document.defaultView.getComputedStyle(element, null).getPropertyValue("position");
          }
        }
        current_element_position = current_element_position.toLowerCase();
        if (current_element_position !== "absolute" && current_element_position !== "relative") {
          return element.className += " chardinjs-relative-position";
        }
      };

      chardinJs.prototype._get_offset = function(element) {
        var element_position, _x, _y;

        element_position = {
          width: element.offsetWidth,
          height: element.offsetHeight
        };
        _x = 0;
        _y = 0;
        while (element && !isNaN(element.offsetLeft) && !isNaN(element.offsetTop)) {
          _x += element.offsetLeft;
          _y += element.offsetTop;
          element = element.offsetParent;
        }
        element_position.top = _y;
        element_position.left = _x;
        return element_position;
      };

      return chardinJs;
    })();
  
    return $.fn.extend({
      chardinstepsjs: function() {
        var $this, args, stepsController, option;

        option = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        $this = $(this[0]);
        stepsController = $this.data('chardinStepsJs');
        if (!stepsController) {
          $this.data('chardinStepsJs', (stepsController = new chardinStepsJs(this, option)));
        }
        
        stepsController.options = {
          click_to_dismiss: true,
          reset_on_resume: false
        };
        
        if (option === Object(option)) {
          $.extend(stepsController.options, option);
        }
        return stepsController;
      }
    });
  })(window.jQuery, window);
}).call(this);
